### ISSUE TITLE
no .mx1 ?

### ISSUE THREAD

**Issue by achtan** [basscss/white-space#3]
Hi
i am missing something like .mx1 .mx2 and so no... and .my1 ...

**Comment by jxnblk** [comment]
You're not missing anything. Margins are only in single directions and padding is symmetrical. That was a conscious design decision, but let me know if that's unclear in the readme/docs.

**Comment by achtan** [comment]
no doc is fine... i just don't get it why is it missing... now i have to use `.ml1 .mr1` ... not a big dial bud it is longer and if I wana change it to `.ml3 .mr3` I must edit 2 numbers ...

**Comment by jxnblk** [comment]
Yeah, if you feel like you'd want that in your project, I'd recommend adding in your own .mx1 etc. extensions.

For me, I generally use padding for anything symmetrical and margins for nudging in one direction. I may change this in the future, but that would be with a major version release.
